redmine_url: ""
api_key: ""
root_folder: "~/logtime"
defaults:
  sync: "77549"
  organization: "77549"
  standup: "77488"
  refinement: "77548"
  review: "77489"
  retro: "77489"
  planning: "77491"
  shift: "77928"
  support: "77928"
  monitoring: "77546"
